name: ビルド frontend/Campus
run-name: "${{ github.actor }} - ${{ github.event.pull_request.title }} (${{ github.head_ref }})"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths: 
      - .github/workflows/build-campus.yml
      - frontend/share/**
      - frontend/campus/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BUILD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          sparse-checkout: |
            frontend/share/
            frontend/campus/

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22.14.0
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json

      - name: npm のセットアップ
        run: |
          npm ci --prefix frontend

      - name: campus のビルド
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
          cd frontend
          npm install
          npm run build --workspace campus

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: frontend-campus
          path: frontend/campus/dist